# Generated by Django 4.2.30 on 2026-07-02 20:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_relatedrecords_file_delete_relatedrecordsfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedrecords',
            name='file',
            field=models.FileField(upload_to=accounts.models.get_related_record_path, verbose_name='Upload file'),
        ),
    ]
